# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns: ["*"]
    commit-message:
      prefix: "ci(deps)"

  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      npm-prod:
        dependency-type: "production"
        update-types: ["minor", "patch"]
      npm-dev:
        dependency-type: "development"
        update-types: ["minor", "patch"]
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
