name: Release

on:
  workflow_dispatch: ~
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC / npm
  contents: read

jobs:
  build:
    name: 'Build & Publish to NPM'
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # use node:6 docker image to build, as v3 is an old version requiring node-gyp with python 2.7
      - name: Build with Node 6 (via Docker)
        run: docker run --rm -v $(pwd):/app -w /app node:6 sh -c "npm install && npm run build"

      # use node 20 to publish
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm publish --tag version-3